stages:
    - pre-merge-check
    - deploy
    - post-deploy-check

pre-merge-check:
  stage: pre-merge-check
  script:
    - export PATH="/home/gitlab-runner/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv shell 3.6.10
    - ./version_check.sh
    - pip3 install --upgrade pip
    - pip3 install -r riscof/requirements.txt -U
    - source /tools/setup.sh
    - git clone https://gitlab.com/incoresemi/riscof-plugins.git
    - python3 -m riscof.main --help
      #    - python3 -m riscof.main setup --refname=riscvOVPsim --dutname=spike_simple
      #    - sed -i 's/riscof/riscof\/riscof-plugins/g' config.ini
      #    - cat config.ini
      #    - python3 -m riscof.main run --config=config.ini --no-browser
    - python3 setup.py sdist
  only:
    refs:
      - merge_requests
  tags:
    - incore-group

deploy:
    stage: deploy
    script:
        - python setup.py sdist
        - python -m twine upload --username $pypiusername --password $pypipassword dist/*
        - python /scratch/version-extract.py
    only:
        refs:
            - master
    tags:
        - incore-group 
    except:
      - schedules

post-deploy-check:
  stage: post-deploy-check
  script:
    - export PATH="/home/gitlab-runner/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv shell 3.6.10
    - pip3 install --upgrade pip
    - pip3 install -U riscof
    - source /tools/setup.sh
    - git clone https://gitlab.com/incoresemi/riscof-plugins.git
    - riscof --help
      #- riscof setup --refname=riscvOVPsim --dutname=spike_simple
      #- sed -i 's/riscof/riscof\/riscof-plugins/g' config.ini
      #- cat config.ini
      #- riscof run --config=config.ini --no-browser
  only:
    refs:
      - master
  tags:
    - incore-group

