/riscof/suite/I-ADD-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-ADDI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-AND-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-ANDI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-AUIPC-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BEQ-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BGE-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BGEU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BLT-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BLTU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-BNE-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRC-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRCI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRS-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRSI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRW-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-CSRRWI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-DELAY_SLOTS-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-EBREAK-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True)
/riscof/suite/I-ECALL-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-ENDIANESS-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-FENCE.I-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-IO.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-JAL-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-JALR-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LB-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LBU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LH-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LHU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LUI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-LW-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-MISALIGN_JMP-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-MISALIGN_LDST-02.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-NOP-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-OR-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-ORI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-RF_size-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-RF_width-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-RF_x0-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SB-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SH-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLL-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLLI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLT-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLTI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLTIU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SLTU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SRA-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SRAI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SRL-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SRLI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SUB-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-SW-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-XOR-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/I-XORI-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32I
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-DIV-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-DIVU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-MUL-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-MULH-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-MULHSU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-MULHU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-REM-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
/riscof/suite/M-REMU-01.S:
  commit_id: 1b7807b5c536b294795b2db0175808a936a96325
  isa: RV32IM
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_CASE_1=True
