/suite/modified/I-ADD-01.S:
  commit_id: d9002a1fac22ebd602b99c4eb3aff4e1715d5dc9
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_PART_1=True
/suite/modified/I-BEQ-01.S:
  commit_id: f0f427d60190a854546cb38af386542d9409b598
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      define:
      - def TEST_PART_1=True
/suite/modified/M-DIV-01.S:
  commit_id: bfabaadefa8b82c29cbc90eab609f8da5475d353
  parts:
    '1':
      check:
      - check ISA:=regex(.*I.*)
      - check ISA:=regex(.*M.*)
      define:
      - def TEST_PART_1=True
